from typing import Annotated, TypedDict

from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    messages: Annotated[list, add_messages]

    # High-level plan generated by the planner
    plan: list[str]

    # Execution tracking
    current_step: int

    # Successfully executed tool results
    tool_results: list[str]

    # Current execution error, if any
    error: str | None
